### ISSUE TITLE
能否加入开机自启动？

### ISSUE THREAD

**Issue by freenaser** [missuo/CloudflareWarp#1]
重启后脚本会失效。

**Comment by missuo** [comment]
实在抱歉，或许我不会加入这个功能。因为如果给机器同时增加了IPV4和IPV6的话，会导致无法建立SSH连接，重启也没办法恢复。为了预防这种现象的产生，我不会增加开机自启动。你可以开机后输入`wg-quick up wgcf`来启动Warp！！！感谢反馈。

**Comment by freenaser** [comment]
> 
> 
> 实在抱歉，或许我不会加入这个功能。因为如果给机器同时增加了IPV4和IPV6的话，会导致无法建立SSH连接，重启也没办法恢复。为了预防这种现象的产生，我不会增加开机自启动。你可以开机后输入`wg-quick up wgcf`来启动Warp！！！感谢反馈。

感谢您的回复，个人认为同时增加V4和V6的几率太小，并不实用，且您在代码中已提示用户可能产生的后果，这个选择权在使用者。另如果您坚持不主动添加自启动，我觉得可以多写一行“是否添加自启动“代码让用户选择。

**Comment by missuo** [comment]
好的 谢谢你的建议
