### ISSUE TITLE
能否增加无损双栈的模式

### ISSUE THREAD

**Issue by lns103** [missuo/CloudflareWarp#2]
[https://hiram.wang/cloudflare-wrap-vps/](https://hiram.wang/cloudflare-wrap-vps/)中提供的方式
在 ``` wgcf.conf ``` 中``` [Interface] ``` 的最后加上
```
PostUp = ip rule add from 本机v4地址 lookup main
PostDown = ip rule delete from 本机v4地址 lookup main
PostUp = ip -6 rule add from 本机v6地址 lookup main
PostDown = ip -6 rule delete from 本机v6地址 lookup main
```
本人测试可以不破坏vps原生v4\v6的ssh和建站等功能，并且出站流量走warp

**Comment by missuo** [comment]
感谢你提供的方案，我尽快加上你提供的「无损双栈模式」

**Comment by missuo** [comment]
> https://hiram.wang/cloudflare-wrap-vps/中提供的方式
> 在 `wgcf.conf` 中`[Interface]` 的最后加上
> 
> ```
> PostUp = ip rule add from 本机v4地址 lookup main
> PostDown = ip rule delete from 本机v4地址 lookup main
> PostUp = ip -6 rule add from 本机v6地址 lookup main
> PostDown = ip -6 rule delete from 本机v6地址 lookup main
> ```
> 
> 本人测试可以不破坏vps原生v4\v6的ssh和建站等功能，并且出站流量走warp

我在配置文件中增加了这些，似乎无法正常出站。还需要改什么吗？

**Comment by lns103** [comment]
我修改配置后使用命令
```wg-quick down wgcf``` 关闭
```wg-quick up wgcf``` 启动
然后就可以使用了😂
ping v4或v6地址、ssh连接等操作都没有问题
使用VPS进行traceroute v4 v6均使用warp地址

这是我目前的配置，关键信息进行了隐藏

``` 
[Interface]
PrivateKey = xxx=
Address = 172.16.x.x/32
Address = fd01::xxxx:6593/128
DNS = 1.1.1.1
MTU = 1280
PostUp = ip rule add from 140.x.x.100 lookup main
PostDown = ip rule delete from 140.x.x.100 lookup main
PostUp = ip -6 rule add from 2001::fb6 lookup main
PostDown = ip -6 rule delete from 2001::fb6 lookup main
[Peer]
PublicKey = xxx+xxx/xxx=
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
Endpoint = 162.159.192.1:2408
```
v4和v6地址都是网卡上获取到的

**Comment by lns103** [comment]
IP测试结果
<Details>


![Screenshot_2021-05-13-00-53-51-642_com android chrome](https://user-images.githubusercontent.com/49310852/118014491-df1a5800-b385-11eb-9ce0-7c3be1553805.jpg)
![Screenshot_2021-05-13-00-53-22-971_com android chrome](https://user-images.githubusercontent.com/49310852/118014504-e2addf00-b385-11eb-9c28-26ad9d5aa781.jpg)
![Screenshot_2021-05-13-00-54-34-801_com android chrome](https://user-images.githubusercontent.com/49310852/118014527-e5103900-b385-11eb-9d10-827398f60b34.jpg)


</Details>

**Comment by missuo** [comment]
我按照你的方法之后，无法解析任何v4和v6的域名 `curl ip.sb` 无返回结果了，请问你的系统是什么，内核是什么版本，是否改过路由表？

**Comment by lns103** [comment]
> 我按照你的方法之后，无法解析任何v4和v6的域名 `curl ip.sb` 无返回结果了，请问你的系统是什么，内核是什么版本，是否改过路由表？

之前使用一键脚本的时候，内核被换为3.10.0-1160.25.1.el7.x86_64，我手动切换至kernel-5.12.2_bbrplus-1.x86_64后出现了相同的问题，我再看看吧😥

**Comment by missuo** [comment]
那你用的是WireGuard还是WireGuard-Go

**Comment by missuo** [comment]
我的Telegram就是@missuo，我们可以TG交流一下！
