### ISSUE TITLE
VPS重装后重新运行脚本，无法成功申请ipv6地址

### ISSUE THREAD

**Issue by 2guan** [missuo/CloudflareWarp#3]
VPS重装后重新运行脚本，无法成功申请ipv6地址
提示以下信息后返回为空值。

2021/05/20 10:47:18 existing account detected
wgcf/cmd/register.registerAccount
	/drone/src/cmd/register/register.go:41
wgcf/cmd/register.glob..func1
	/drone/src/cmd/register/register.go:27
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
wgcf/cmd.Execute
	/drone/src/cmd/root.go:36
main.main
	/drone/src/main.go:10
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
2021/05/20 10:47:18 Using config file: wgcf-account.toml

**Comment by missuo** [comment]
请提供你的VPS的系统版本以及内核版本

**Comment by missuo** [comment]
可能是你的IP被Cloudflare加入黑名单了 暂时没有解决方案

**Comment by 2guan** [comment]
1小时前运行脚本的时候刚刚通过。刚刚重置了一下VPS，重新运行脚本，就报错了。
系统是DEBIAN10，内核版本5.11.4。

**Comment by missuo** [comment]
频繁申请可能会被拉黑，建议你过段时间再试试。

**Comment by 2guan** [comment]
如果重装VPS，只能重新申请么？是否有先注销或者直接找回之前地址的方式？

**Comment by missuo** [comment]
你有之前的配置文件吗

**Comment by 2guan** [comment]
找到问题了。是默认没有安装curl 😄

**Comment by missuo** [comment]
好的 我加一个 谢谢
