### ISSUE TITLE
Centos7 单独申请ipv6后有下发IP但是curl是V4地址

### ISSUE THREAD

**Issue by zhucaidan** [missuo/CloudflareWarp#4]
Centos7 内核5.12.6
仅增加IPV6下申请Ipv6有以下提示：

“本机IPV6: 2a09:bac0:xxxxxxxxx
恭喜你！配置完成！感谢使用! Have a nice day :)”

之后使用curl -6 ip.sb得到的返回结果却是本机原始ipv4的IP，而且无法ping通ipv6的ip

“ping 2606:4700:4700::1111
ping: 2606:4700:4700::1111: 不支持的主机名地址族”

**Comment by zhucaidan** [comment]
已解决，BBR加速脚本里要开启一下ipv6

**Comment by zhucaidan** [comment]
还有个小问题就是单独申请ipv6后，/etc/resolv.conf 会被锁定1.1.1.1为DNS，但是并没有加入2606:4700:4700::1111，所以解析v6的域名会出现问题

**Comment by sjlleo** [comment]
事实上并不会这样，因为只要是DNS是可以同时返回IPv4和IPv6的双栈结果的。
如果您要执意要加上IPv6的DNS的话，可以在 /etc/wireguard/wgcf.conf 里面修改为
`DNS = 1.1.1.1, 2606:4700:4700::1111`
然后重启WireGuard，`wg-quick down wgcf && wg-quick up wgcf`
