### ISSUE TITLE
arm64无法添加IPV4

### ISSUE THREAD

**Issue by libsgh** [missuo/CloudflareWarp#5]
你选择了增加 IPV4 的模式
开始自动修改配置文件
开始加载WireGuard内核模块
cp: cannot create regular file '/etc/wireguard/wgcf.conf': No such file or directory
开启启动WireGuard隧道
warp.sh: line 135: wg-quick: command not found
WireGuard隧道启动完成

**Comment by missuo** [comment]
是的，ARM64还在测试阶段。我用Oracle的机器也无法增加。原因是WireGuard不支持ARM。

**Comment by libsgh** [comment]
> 是的，ARM64还在测试阶段。我用Oracle的机器也无法增加。原因是WireGuard不支持ARM。

我使用的oracle linux 8, 参考下这个脚本 https://github.com/YG-tsj/Oracle-warp
我不知道怎么升级内核，貌似新版内核可以？
![image](https://user-images.githubusercontent.com/25656088/120467735-0a1b2900-c3d3-11eb-8a9e-bc1506066e99.png)

**Comment by missuo** [comment]
之后会考虑使用Go的版本来支持ARM64
