### ISSUE TITLE
希望注明原帖作者与脚本无关

### ISSUE THREAD

**Issue by luminouskk** [missuo/CloudflareWarp#6]
近期已经有几位朋友来询问我有关您的脚本存在的问题了……

一脸懵，嘤嘤嘤(ToT)/~~~

希望您在注明原帖的时候，注明原帖与脚本无关，或者注明原作者，谢谢啦~

**Comment by missuo** [comment]
好的 谢谢你

**Comment by Rail-gun** [comment]
哈哈哈，我刚刚问了一遍
