### ISSUE TITLE
Debian10系统BUG

### ISSUE THREAD

**Issue by tianyunb666** [missuo/CloudflareWarp#7]
Debian10系统需要运行2次脚本才生效
第一次运行脚本不会生效 PS：第一次运行没效果 然后第二次运行脚本选择2 然后ipv6才生效
作者能不能帮忙解决

还有就是 能不能加个开机自启 要不然重启VPS ipv6就不生效 要手动加开机运行命令才能

**Comment by missuo** [comment]
不会生效提示什么

**Comment by tianyunb666** [comment]
第一次运行脚本 如果输入2 显示如下

root@debian:~# wget -O warp.sh https://cdn.jsdelivr.net/gh/missuo/CloudflareWarp/warp.sh && bash warp.sh
--2021-06-08 12:13:20--  https://cdn.jsdelivr.net/gh/missuo/CloudflareWarp/warp.sh
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 104.16.89.20, 104.16.85.20, 104.16.88.20, ...
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|104.16.89.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-sh]
Saving to: ‘warp.sh’

warp.sh                             [ <=>                                                    ]   8.19K  --.-KB/s    in 0s      

2021-06-08 12:13:20 (66.8 MB/s) - ‘warp.sh’ saved [8386]

现在开始检查你的系统是否支持
系统版本为: Debian 10 x64 内核版本为: 5.12.9
检查通过 该系统支持安装Cloudflare Warp
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u1).
wget is already the newest version (1.20.1-1.1).
The following packages were automatically installed and are no longer required:
  apparmor file libmagic-mgc libmagic1 libmpdec2 libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib libreadline7
  libsqlite3-0 mime-support python3 python3-minimal python3.7 python3.7-minimal
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  net-tools openresolv sudo
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,516 kB of archives.
After this operation, 4,978 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1 [248 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 openresolv amd64 3.8.0-1 [22.9 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 sudo amd64 1.8.27-1+deb10u3 [1,244 kB]
Fetched 1,516 kB in 0s (36.1 MB/s)
Selecting previously unselected package net-tools.
(Reading database ... 36146 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60+git20180626.aebd88e-1_amd64.deb ...
Unpacking net-tools (1.60+git20180626.aebd88e-1) ...
Selecting previously unselected package openresolv.
Preparing to unpack .../openresolv_3.8.0-1_amd64.deb ...
Unpacking openresolv (3.8.0-1) ...
Selecting previously unselected package sudo.

Cloudflare Warp 一键安装脚本 Made by missuo
更新内容及反馈： https://github.com/missuo/CloudflareWarp
————————————模式选择————————————
1. 仅增加IPV4 [推荐]
2. 仅增加IPV6 [推荐]
3. 同时增加IPV4 & IPV6[慎用]
4. 同时增加IPV4 & IPV6[无损模式]
0. 退出脚本
————————————————————————————————
 请输入数字: 2
开始注册Cloudflare Warp账号
--2021-06-08 12:13:30--  https://cdn.jsdelivr.net/gh/missuo/CloudflareWarp/CDNRelease/wgcf_2.2.3_linux_amd64
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 104.16.88.20, 104.16.89.20, 104.16.86.20, ...
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|104.16.88.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8454144 (8.1M) [application/octet-stream]
Saving to: ‘wgcf’

wgcf                            100%[=======================================================>]   8.06M  --.-KB/s    in 0.04s   

2021-06-08 12:13:30 (181 MB/s) - ‘wgcf’ saved [8454144/8454144]

2021/06/08 12:13:30 Using config file: wgcf-account.toml
This project is in no way affiliated with Cloudflare
Cloudflare's Terms of Service: https://www.cloudflare.com/application/terms/
✔ Yes
2021/06/08 12:13:35 =======================================
2021/06/08 12:13:35 Device name   : 10FE7F

本机IPV6: 

恭喜你！配置完成！感谢使用! Have a nice day :)


第一次再运行脚本 然后输入2 就获取到ipv6了

**Comment by missuo** [comment]
我目前手头没有Debian10的机器。我明天有空试一下吧。开机自启我尽快支持。

**Comment by tianyunb666** [comment]
# 启用守护进程
sudo systemctl start wg-quick@wgcf
# 设置开机启动
sudo systemctl enable wg-quick@wgcf

目前使用的开机自启命令

**Comment by ChellyL** [comment]
我也遇到类似问题，第一次提示安装成功但没有显示ipv6地址，要安装两次：
*************************************
已完成注册 即将执行下一步操作
你选择了增加 IPV6 的模式
开始自动修改配置文件
开始加载WireGuard内核模块
开启启动WireGuard隧道
……中略……
WireGuard隧道启动完成
开始检测本机IPV6

本机IPV6: 

恭喜你！配置完成！感谢使用! Have a nice day :)

root@racknerd-1593d1:~# curl ipv6.ip.sb
curl: (7) Couldn't connect to server

******************************
这个问题似乎和我机器没有开启ipv6有关……

**Comment by missuo** [comment]
感谢反馈。已解决。
