### ISSUE TITLE
WARP 使用

### ISSUE THREAD

**Issue by LexterS999** [missuo/CloudflareWarp#8]
我可以在我的 VPS 上使用 WARP 加速嗎，因為我只有 Ipv4，而且我正在使用 xray+grpc/tls+CDN。 我不想使用 WireGuard，因為它在我的國家完全被封鎖。

**Comment by missuo** [comment]
> 我可以在我的 VPS 上使用 WARP 加速嗎，因為我只有 Ipv4，而且我正在使用 xray+grpc/tls+CDN。 我不想使用 WireGuard，因為它在我的國家完全被封鎖。
感谢你的支持。你可以告诉我你想实现什么功能吗？解封流媒体？还是想让你的VPS拥有IPv6？

**Comment by LexterS999** [comment]
我的 VPS 位於德國，它為我提供了對所需站點的完全訪問權限。 因為我放了xray+grpc+CDN，不需要虛擬ipv6，因為有真正的ipv6。 但如果可能的話，我想使用扭曲速度來加速我的連接。 如果可以用 xray+grpc+CDN 連接 WARP

我的國家完全阻止了 UDP，這就是為什麼我主要使用 xray+grpc+CDN 作為 TCP

**Comment by LexterS999** [comment]
這是我的 VPS 上的 vless+grpc 配置，所以我可以使用腳本安裝的 WARP 嗎？

{
     “入站”：[
     {
         “端口”：xxxxxx，
         “聽”：“127.0.0.1”，
         “協議”：“vless”，
         "tag":"VLESSGRPC",
         “設置”：{
             “客戶”：[
                 {
                     "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
                     "添加": "xxxxxx",
                     "email": "xxxxxxxxxxxxxxx"
                 }
             ],
             “解密”：“無”
         },
         “流設置”：{
             “網絡”：“grpc”，
             “grpc設置”：{
                 “服務名稱”：“xxxxxxxxxxxxxxx”
             }
         }
     }
]
}

**Comment by missuo** [comment]
你可以联系我的Telegarm。[missuo](https://t.me/missuo)
