### ISSUE TITLE
ipv6 检测有误

### ISSUE THREAD

**Issue by ChellyL** [missuo/CloudflareWarp#9]
如题，ip.sb的ipv6检测api似乎有问题？
我通过脚本添加了ipv6后，最后检测出的ipv6地址和whatismyipaddress.com上检测的ip不一致？

**Comment by missuo** [comment]
请问是哪里有误？curl ipv6.ip.sb吗

**Comment by ChellyL** [comment]
对对，抱歉刚才写issue的时候手快没写完就发出去了

**Comment by missuo** [comment]
ip.sb应该还是挺准的

**Comment by ChellyL** [comment]
![图片](https://user-images.githubusercontent.com/38887991/124704682-0b39fb80-df27-11eb-88ab-e971d8476892.png)
![Snipaste_2021-07-07_13-27-35](https://user-images.githubusercontent.com/38887991/124704835-4e946a00-df27-11eb-9261-2c6bda9933ab.png)

用 ip.sb 和 p3terx.com以及whatismyipaddress.com测出来的……
